from gpt import GPT
from gpt.tools import full_path
#from .astra import recommended_spacecharge_mesh

from distgen import Generator   
from distgen.writers import write_gpt
from distgen.tools import update_nested_dict

import json
import os

def set_gpt_and_distgen(gpt, distgen_input, settings, verbose=False):
    """
    Searches gpt and distgen input for keys in settings, and sets their values to the appropriate input.
    """
    for k, v in settings.items():
        found=gpt.set_variable(k,v)
        if verbose:
            print(k, 'is in gpt', nl)
        
        if not found:
            distgen_input = update_nested_dict(distgen_input, {k:v}, verbose=verbose)
            #set_nested_dict(distgen_input, k, v)    
    
    return gpt, distgen_input
    
def run_gpt_with_distgen(settings=None,
                         gpt_input_file=None,
                         distgen_input_file=None,
                         workdir=None, 
                         gpt_bin='$GPT_BIN',
                         timeout=2500,
                         verbose=False,
                         ):
    """
    Run gpt with particles generated by distgen. 
    
        settings: dict with keys that can appear in an gpt or distgen Generator input file. 
        
    Example usage:
        A = run_gpt_with_distgen({'lspch':False},
                       gpt_input_file='$LCLS_LATTICE/gpt/models/gunb_eic/gpt.in',
                       distgen_input_file='$LCLS_LATTICE/distgen/models/gunb_gaussian/gunb_gaussian.json',
                       verbose=True,
                       timeout=None
                      )        
        
    """

    # Call simpler evaluation if there is no generator:
    if not distgen_input_file:
        return run_gpt(settings=settings, 
                         gpt_input_file=gpt_input_file, 
                         workdir=workdir,
                         gpt_bin=gpt_bin, 
                         timeout=timeout, 
                         verbose=verbose)
        
    
    if verbose:
        print('run_gpt_with_generator') 

    # Make gpt and generator objects
    G = GPT(gpt_bin=gpt_bin, input_file=gpt_input_file, workdir=workdir)
    G.timeout=timeout
    G.verbose = verbose
    
    # Distgen generator
    gen = Generator(verbose=verbose)
    f = full_path(distgen_input_file)
    distgen_params = json.load(open(f))
    
    
    # Link particle files
    particle_file = 'distgen_gpt_particles.gdf'
    #G.input['newrun']['distribution'] = particle_file
    #G.input['newrun']['l_rm_back'] = True # Remove backwards particles
    
    print(particle_file )
    
    # Set inputs
    if settings:
        G, distgen_params = set_gpt_and_distgen(G, distgen_params, settings, verbose=verbose)

    
    # Configure distgen
    gen.parse_input(distgen_params)       
    
    # Run
    beam = gen.beam()
    particle_file = os.path.join(G.path, particle_file)
    write_gpt(beam, particle_file, verbose=verbose)
    
    G.run()
    
    return G


def evaluate_astra_with_distgen(settings, archive_path=None, merit_f=None, **run_astra_with_distgen_params):
    """
    Simple evaluate astra.
    
    Similar to run_astra_with_distgen, but returns a flat dict of outputs. 
    
    Will raise an exception if there is an error. 
    
    """
    A = run_astra_with_distgen(settings, **run_astra_with_distgen_params)
        
    if merit_f:
        output = merit_f(A)
    else:
        output = default_astra_merit(A)
    
    if output['error']:
        raise
    
    fingerprint = A.fingerprint()
    
    output['fingerprint'] = fingerprint
    
    if archive_path:
        path = full_path(archive_path)
        assert os.path.exists(path), f'archive path does not exist: {path}'
        archive_file = os.path.join(path, fingerprint+'.h5')
        A.archive(archive_file)
        output['archive'] = archive_file
        
    return output
