&tao_start
  n_universes = 1
/




!--------------------------------------------------------
&tao_design_lattice
  design_lattice(1)%file='fodo.lat.bmad'

/

!------------------------------------------------------------------------
&tao_params
  !global%plot_on = T
  global%track_type = 'single'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! or: 'quasi'
  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  global%var_out_file = ''
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = F
/

!--------------------------------------------------------
!------------------BEAM-------------------------------
&tao_beam_init
  beam_init%n_particle = 10000
  beam_init%random_engine = 'quasi'
  !beam_init%random_engine = 'pseudo'
  ix_universe = 1
  beam_saved_at =  "MARKER::*"
 
 track_start = 'BEGINNING'
 track_end   = 'END'
 beam_init%position_file = 'x_probe_particle.h5'

!  beam_dump_file = 'beam_dump.h5'
!  beam_dump_at = 'm_*'
  beam_init%a_norm_emit = 0.7e-6
  beam_init%b_norm_emit = 0.7e-6
  beam_init%dPz_dz = 0.0
  beam_init%n_bunch = 1     
  beam_init%bunch_charge = 40e-12
  beam_init%sig_pz = 2.5e-4
  beam_init%sig_z = 0.0006 ! 2 ps * c
  
  ! comb_ds_save = 0.002
/








!&tao_d2_data
!        d2_data%name = 'match'
!        universe = 1
!        n_d1_data = 1
!/

!&tao_d1_data
!    ix_d1_data = 1
!    d1_data%name = 'etas'
!    datum( 1) =  'eta.x'      '' 'beginning' 'MG.Mar.MID'   'target'   0  1e2
!    datum( 2) =  'eta.y'      '' 'beginning' 'MG.Mar.MID'   'target'   0  1e2
!    datum( 3) =  'eta.x'      '' 'beginning' 'MG.Mar.END'   'target'   0  1e2
!    datum( 4) =  'eta.y'      '' 'beginning' 'MG.Mar.END'   'target'   0  1e2
!
!/ 

!&tao_var
!   v1_var%name = "sol" 
!   search_for_lat_eles = "solenoid::*" 
!   default_step = 1e-4 
!   default_attribute = "ks" 
!!   default_attribute = "bs_field" 
! !  default_merit_type = "limit" 
! !  default_low_lim = -10 
! !  default_high_lim = 10
!   default_weight = 1
!   ix_min_var = 1 
!   default_key_delta = 1e-3
!   default_key_bound = T
!/

!------------------------------------------------------------------------

&tao_var
    v1_var%name = 'begtwiss'
    default_step = 1e-4
    default_universe = '1'
    ix_min_var = 1
    ix_max_var = 6
    var(1:6)%ele_name  = 'beginning', 'beginning', 'beginning', 'beginning', 'beginning', 'beginning'
    var(1:6)%attribute = 'beta_a', 'alpha_a', 'beta_b', 'alpha_b', 'eta_x', 'etap_x'
    var(1)%low_lim = 0.01
    var(3)%low_lim = 0.01
/
